# Generated by Django 5.1.4 on 2024-12-11 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Sneakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('img', models.ImageField(upload_to='images')),
                ('obj_3d', models.FileField(upload_to='files')),
                ('price', models.PositiveIntegerField(default=999)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shapp.firm')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('sneakers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shapp.sneakers')),
            ],
        ),
    ]
