# Generated by Django 5.1.4 on 2024-12-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
